# Site settings
title: Biswaranjan Pati
description: Creative Project Manager at NIC, HQ, New Delhi
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Biswaranjan Pati
user_description: Creative Project Manager at NIC, HQ, New Delhi.
user_title: Creative Project Manager
email: biswaranjanpati6804@gmail.com
twitter_username: biswaranjanpati
github_username:  biswaranjanpati
gplus_username:  u/0/+BiswaranjanPati6804

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
